server:
  port: 8081

spring:
  application:
    name: catalog-service
  mongodb:
    uri: ${MONGO_URI:mongodb://localhost:27017/streamflix_db}
  data:
    redis:
      host: ${REDIS_HOST:localhost} # Uses localhost for local IDE, or docker host
      port: 6379    

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

      

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Opens all actuator endpoints (health, metrics, etc.)
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
