# docker-compose.yml
services:
  # 1. PostgreSQL (For User & Rating Services)
  postgres:
    image: postgres:16-alpine
    container_name: streamflix-postgres
    environment:
      POSTGRES_USER: streamflix_user
      POSTGRES_PASSWORD: streamflix_pass
      POSTGRES_DB: streamflix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB (For Catalog Service)
  mongodb:
    image: mongo:7.0
    container_name: streamflix-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Redis (For caching and fast watch-state retrieval)
  redis:
    image: redis:7-alpine
    container_name: streamflix-redis
    ports:
      - "6379:6379"

  # 4. Apache Kafka (Official Image, KRaft Mode)
  kafka:
    image: apache/kafka:3.7.0
    container_name: streamflix-kafka
    ports:
      - "9094:9094" # Port for your local IDE to connect
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'StreamFlixCluster12345'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # 5. Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: streamflix-kafka-ui
    ports:
      - "8090:8080" # Available at localhost:8090
    environment:
      - KAFKA_CLUSTERS_0_NAME=StreamFlix-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

volumes:
  postgres_data:
  mongo_data: