# docker-compose-full.yml
# docker compose -f docker-compose-full.yml up --build
services:

  # ==========================================
  # 1. INFRASTRUCTURE & DATABASES
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: streamflix-postgres
    environment:
      POSTGRES_USER: streamflix_user
      POSTGRES_PASSWORD: streamflix_pass
      POSTGRES_DB: streamflix_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7.0
    container_name: streamflix-mongo
    ports:
      - "27017:27017"

  kafka:
    image: apache/kafka:3.7.0
    container_name: streamflix-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      # Notice we expose internal port 9092 for other containers to connect to
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'StreamFlixCluster12345'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # ==========================================
  # 2. NETFLIX DISCOVERY (EUREKA)
  # ==========================================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=eureka-server

  # ==========================================
  # 3. MICROSERVICES (DGS SUBGRAPHS)
  # ==========================================
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/streamflix_db
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
    depends_on:
      - mongodb
      - eureka-server
      - otel-collector

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/streamflix_db
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - eureka-server

  rating-service:
    build: ./rating-service
    container_name: rating-service
    ports:
      - "8083:8083"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/streamflix_db
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - KAFKA_URL=kafka:9092
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - kafka
      - eureka-server

  playback-service:
    build: ./playback-service
    container_name: playback-service
    ports:
      - "8086:8086"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/streamflix_db
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - eureka-server

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - KAFKA_URL=kafka:9092
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - kafka
      - eureka-server

  # ==========================================
  # 4. APOLLO FEDERATION GATEWAY
  # ==========================================
  federation-gateway:
    build: ./federation-gateway
    container_name: federation-gateway
    ports:
      - "4000:4000"
    environment:
      - CATALOG_URL=http://catalog-service:8081/graphql
      - USER_URL=http://user-service:8082/graphql
      - RATING_URL=http://rating-service:8083/graphql
      - PLAYBACK_URL=http://playback-service:8086/graphql
    restart: on-failure   
    depends_on:
      - catalog-service
      - user-service
      - rating-service
      - playback-service


# ==========================================
# 5. FRONTEND UI (REACT + NGINX)
# ==========================================
  streamflix-ui:
    build: ./streamflix-ui
    container_name: streamflix-ui
    # We map port 3000 on your machine to Nginx's internal port 80
    ports:
      - "3000:80"
    depends_on:
      - federation-gateway      


  zipkin:
    image: openzipkin/zipkin:latest
    container_name: streamflix-zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.143.1
    container_name: streamflix-otel-collector
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./otel-collector/config.yaml:/etc/otel-collector/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - zipkin