server:
  port: 8083

spring:
  application:
    name: rating-service
  
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/streamflix_db
    username: streamflix_user
    password: streamflix_pass
    driver-class-name: org.postgresql.Driver
  
  # JPA / Hibernate settings to auto-create your tables during development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/