server:
  port: 8082

spring:
  application:
    name: user-service
  
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/streamflix_db
    username: streamflix_user
    password: streamflix_pass
    driver-class-name: org.postgresql.Driver
  
  # JPA / Hibernate settings to auto-create your tables during development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/