apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: user-service }
  template:
    metadata:
      labels: { app: user-service }
    spec:
      containers:
        - name: user
          image: streamflix/user-service
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8082, name: http }]
          env:
            - { name: POSTGRES_URL, value: "jdbc:postgresql://postgres:5432/streamflix_db" }
            - { name: EUREKA_URL, value: "http://eureka-server:8761/eureka/" }
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: streamflix-secrets, key: JWT_SECRET }
            - { name: OTLP_TRACES_ENDPOINT, value: "http://otel-collector:4318/v1/traces" }
            - { name: OTLP_LOGS_ENDPOINT, value: "http://otel-collector:4318/v1/logs" }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests: { memory: 512Mi, cpu: 200m }
            limits: { memory: 1Gi, cpu: 1000m }
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector: { app: user-service }
  ports:
    - { port: 8082, targetPort: 8082, name: http }
